### ISSUE TITLE
донт ворк

### ISSUE THREAD

**Issue by uselessuserhere** [AKonLegend/vk-slaves-python-bot#1]
при запуске `py3 run.py`

```
Traceback (most recent call last):
  File "C:\Users\test\OneDrive\Рабочий стол\vk-slaves-python-bot-main\run.py", line 10, in <module>
    client = Slaves(token)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_slaves\slaves.py", line 25, in __init__
    url = get["response"]["mobile_iframe_url"]
KeyError: 'mobile_iframe_url'
```
 на чей стороне ошибка?

**Comment by 3aTo4Ka** [comment]
> при запуске `py3 run.py`
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\test\OneDrive\Рабочий стол\vk-slaves-python-bot-main\run.py", line 10, in <module>
>     client = Slaves(token)
>   File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_slaves\slaves.py", line 25, in __init__
>     url = get["response"]["mobile_iframe_url"]
> KeyError: 'mobile_iframe_url'
> ```
> 
> на чей стороне ошибка?

Поменяй токен.

**Comment by uselessuserhere** [comment]
> Поменяй токен

заработало, спасибо. закрыто

![image](https://user-images.githubusercontent.com/81318971/112391999-30a54f80-8d12-11eb-9056-fd1129449975.png)

**Comment by uselessuserhere** [comment]
пришлось переоткрыть

лог как бы показывает, что рабы оцепеняются, но в игре ничего не происходит, и никакие рабы не появляются, что делать? токен свой, айди (от страницы) свой
![image](https://user-images.githubusercontent.com/81318971/112392901-a2ca6400-8d13-11eb-922a-f90ab8f1e054.png)
