### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FlameProfi** [AKonLegend/vk-slaves-python-bot#10]
![image](https://user-images.githubusercontent.com/57589034/112748975-11374c80-8fc
![image](https://user-images.githubusercontent.com/57589034/112748976-1399a680-8fc8-11eb-979c-e3f843166bc3.png)

**Comment by FlameProfi** [comment]
i fixed

**Comment by Tenaret** [comment]
> 
> 
> i fixed

How?

**Comment by tumkas** [comment]
> i fixed

tell please how did you fix it?

**Comment by FlameProfi** [comment]
> > i fixed
> 
> tell please how did you fix it?

https://github.com/FlameProfi/vk-slaves

**Comment by FlameProfi** [comment]
> > i fixed
> 
> How?

https://github.com/FlameProfi/vk-slaves

**Comment by tumkas** [comment]
> https://github.com/FlameProfi/vk-slaves
oh really works but there is a new version v5, and it has this error too(

**Comment by FlameProfi** [comment]
> > https://github.com/FlameProfi/vk-slaves
> > oh really works but there is a new version v5, and it has this error too(

Open issue in my project, i help you
